---

- name: Create ramdisk generation directory
  file:
    path: '{{ ramdisk_prefix | default("") }}/{{ item }}'
    recurse: yes
    state: directory
  with_items:
    - '{{ ramdisk_scripts_location }}'
    - '{{ ramdisk_target }}'
    - 'etc/initramfs-tools/scripts/tmpfs-bottom'

- name: generate ramdisk exclude file
  template:
    src: '{{ item.src }}'
    dest: '{{ ramdisk_prefix | default("")}}/{{ item.dest | default(item.src) }}'
  with_items:
    - src: boot/ramdisk/files-to-exclude
    - src: boot/ramdisk/ramdisk.conf
    - src: boot/ramdisk/overlay.yml

- name: install parallel compression packages
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600
  with_items:
    - pigz
      
- name: copy ramdisk tool
  copy:
    src: '{{ item.src }}'
    dest: '{{ ramdisk_prefix | default("") }}{{ item.dest | default("/" + item.src)}}'
    mode: '0755'
  with_items:
    - src: boot/ramdisk/deploy-ramdisk
    - src: boot/ramdisk/update-ramdisk
    - src: boot/ramdisk/ramdisk-grub
    - src: boot/ramdisk/overlay

- name: link ramdisk tools
  file:
    src: '/boot/ramdisk/{{ item }}'
    dest: '{{ ramdisk_prefix | default("") }}/usr/sbin/{{ item }}'
    state: link
    force: yes
  with_items:
    - update-ramdisk
    - deploy-ramdisk

- include: iso.yml
  when: ramdisk_iso_file is defined

# - name: copy overlay definition file
#   copy:
#     src: '{{ ramdisk_overlay }}'
#     dest: /etc/overlays
#     mode: '0600'
#     owner: root
#     group: root
#   when: ramdisk_overlay is defined
  
- include: initramfs.yml
- include: build-ramdisk.yml
