---

- name: Create ramdisk generation directory
  file:
    path: '{{ ramdisk_prefix | default("") }}/{{ item }}'
    recurse: yes
    state: directory
  with_items:
    - '{{ ramdisk_scripts_location }}'
    - '{{ ramdisk_target }}'
    - 'etc/initramfs-tools/scripts/tmpfs-bottom'

- name: generate ramdisk exclude file
  template:
    src: '{{ item.src }}'
    dest: '{{ ramdisk_prefix | default("")}}/{{ item.dest | default(item.src) }}'
  with_items:
    - src: boot/ramdisk/files-to-exclude
    - src: boot/ramdisk/ramdisk.conf
    
- name: copy update-ramdisk tool
  copy:
    src: boot/ramdisk/update-ramdisk
    dest: '{{ ramdisk_prefix | default("") }}/boot/ramdisk/update-ramdisk'
    mode: '0755'

- name: link update-ramdisk
  file:
    src: /boot/ramdisk/update-ramdisk
    dest: '{{ ramdisk_prefix | default("") }}/usr/sbin/update-ramdisk'
    state: link
    force: yes

- include: iso.yml
  when: ramdisk_iso_file is defined
    
- include: initramfs.yml
- include: build-ramdisk.yml
