#!/bin/sh

# ensure /etc/fstab exists in target filesytem otherwise boot fails before
# mountall.


PREREQ=""
prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
    ;;
esac


fstab=${rootmnt}/etc/fstab

if ! test -e $fstab; then
    touch $fstab || true

    mountpoint='/boot'
    if test -n "${boot_prefix}"; then
	mountpoint=/boot-volume
	mkdir -p ${rootmnt}/${mountpoint}
    fi
    if test -n "$tmpfs_boot"; then
	local mp="$mountpoint"
	if test -n "$tmpfs_boot_prefix"; then
	    mp=/boot-device
	    mkdir -p $rootmnt/$mp
	fi
	if test $fs_type != 'iso9660'; then
	    echo "$tmpfs_boot $mp $fs_type rw 0 0" >> ${rootmnt}/etc/fstab
	fi
    fi
fi
