#!/bin/sh


PREREQ="ensure-fstab ensure-wtmp"
prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
	;;
esac


# Make sure no interface are set with "allow-hotplug" at boot time
sed -i 's/allow-hotplug/auto/' ${rootmnt}/etc/network/interfaces
