#!/bin/sh


PREREQ="fix-network-interface"
prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
	;;
esac

#set -x

if test -e /scripts/functions; then
    . /scripts/functions
fi

if test -x ${rootmnt}/boot/ramdisk/overlay; then
    log_begin_msg "Running overlay script"
    chroot ${rootmnt} /boot/ramdisk/overlay
    if test $? -eq 0; then
	log_end_msg "OK"
    else
	log_error_msg "Failed"
    fi
fi
