#!/bin/sh

. /usr/share/initramfs-tools/hook-functions
. "$CONFDIR/initramfs.conf"

#manual_add_modules iwlmvm
copy_modules_dir kernel/drivers/net/wireless
copy_exec /sbin/wpa_supplicant

cp "$CONFDIR/etc/wpa_supplicant.conf" $DESTDIR/etc/
