#!/bin/sh

target=$1

if test -z "$target"; then
    echo "$0 TARGET_HOST [network]"
    exit 1
fi

network=$2

rsync -ai --progress  --rsync-path 'sudo rsync' /boot/* $target:/boot/

dns0=$(grep '^nameserver ' /etc/resolv.conf | awk '{print $2}' | sort -u | sed -n '1p')
dns1=$(grep '^nameserver ' /etc/resolv.conf | awk '{print $2}' | sort -u | sed -n '2p')


cat <<EOF | ssh $target sudo sh -
sed '/copy_to_boot=/d;' -i /boot/ramdisk/ramdisk.conf
echo "copy_to_boot=yes" >> /boot/ramdisk/ramdisk.conf
sed -i 's/^\(set -e\)/# \1/' /usr/sbin/grub-mkconfig
ln -nfs /boot/ramdisk/ramdisk-grub /etc/grub.d/09-ramdisk

if test -n "$network"; then
  ip_device=eth0
  ip_hostname=\$(hostname -f)
  ip_addr=\$(ifconfig \$ip_device | grep 'inet addr:' | sed -n 's/.*addr:\\([^[:space:]]\\+\\).*/\\1/p')
  ip_mask=\$(ifconfig \$ip_device | grep 'inet addr:' | sed -n 's/.*Mask:\\([^[:space:]]\\+\\).*/\\1/p')
  ip_gw_ip=\$(ip -4 route list 0/0 | awk '{print \$3}')
  
  sed -i "s/^grub_ip_client_ip=.*/grub_ip_client_ip='\$ip_addr'/" /boot/ramdisk/ramdisk.conf
  sed -i "s/^grub_ip_netmask=.*/grub_ip_netmask='\$ip_mask'/" /boot/ramdisk/ramdisk.conf
  sed -i "s/^grub_ip_device=.*/grub_ip_device='\$ip_device'/" /boot/ramdisk/ramdisk.conf
  sed -i "s/^grub_ip_hostname=.*/grub_ip_hostname='\$ip_hostname'/" /boot/ramdisk/ramdisk.conf
  sed -i "s/^grub_ip_gw_ip=.*/grub_ip_gw_ip='\$ip_gw_ip'/" /boot/ramdisk/ramdisk.conf
  sed -i "s/^grub_ip_dns0_ip=.*/grub_ip_dns0_ip='$dns0'/" /boot/ramdisk/ramdisk.conf
  sed -i "s/^grub_ip_dns1_ip=.*/grub_ip_dns1_ip='$dns1'/" /boot/ramdisk/ramdisk.conf
fi
update-grub
EOF
