#!/bin/sh

PREREQ="plymouth"

prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

# We don't really need plymouth here since its use compromise the
# crypsetup root filesystem unlocking.
#
# See: https://bugs.launchpad.net/ubuntu/+source/cryptsetup/+bug/595648
plymouth=$(pidof plymouthd)
if test -n "$plymouth"; then
    echo -n "Killing plymouth ..."
    plymouth --quit
    echo " done"
fi
