#!/bin/sh

# ensure /var/log/wtmp exists in target filesytem otherwise lastlog would
# not be effective.


PREREQ="udev"
prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
    ;;
esac


wtmp=${rootmnt}/var/log/wtmp

if ! test -e $wtmp; then
    touch $wtmp || true
fi
