#!/bin/sh

PREREQ=""

prereqs() {
	echo "$PREREQ"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /scripts/functions

[ -r /var/run/wpa_supplicant.pid ] || exit 0

log_begin_msg "Stopping wpa_supplicant"

kill `cat /var/run/wpa_supplicant.pid`

log_end_msg
